// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (name, type_id, file_path, description, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, type_id, file_path, description, is_active, created_at, updated_at
`

type CreateTemplateParams struct {
	Name        string      `json:"name"`
	TypeID      uuid.UUID   `json:"type_id"`
	FilePath    string      `json:"file_path"`
	Description pgtype.Text `json:"description"`
	IsActive    pgtype.Bool `json:"is_active"`
}

// Templates
func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.Name,
		arg.TypeID,
		arg.FilePath,
		arg.Description,
		arg.IsActive,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.FilePath,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
UPDATE templates SET is_active = false WHERE id = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplate, id)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, name, type_id, file_path, description, is_active, created_at, updated_at FROM templates WHERE id = $1
`

func (q *Queries) GetTemplateByID(ctx context.Context, id uuid.UUID) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, id)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.FilePath,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateWithType = `-- name: GetTemplateWithType :one
SELECT t.id, t.name, t.type_id, t.file_path, t.description, t.is_active, t.created_at, t.updated_at, dt.name as type_name, dt.category
FROM templates t
JOIN document_types dt ON t.type_id = dt.id
WHERE t.id = $1
`

type GetTemplateWithTypeRow struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	TypeID      uuid.UUID          `json:"type_id"`
	FilePath    string             `json:"file_path"`
	Description pgtype.Text        `json:"description"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TypeName    string             `json:"type_name"`
	Category    DocumentCategory   `json:"category"`
}

func (q *Queries) GetTemplateWithType(ctx context.Context, id uuid.UUID) (GetTemplateWithTypeRow, error) {
	row := q.db.QueryRow(ctx, getTemplateWithType, id)
	var i GetTemplateWithTypeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.FilePath,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TypeName,
		&i.Category,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, type_id, file_path, description, is_active, created_at, updated_at FROM templates
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TypeID,
			&i.FilePath,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByType = `-- name: ListTemplatesByType :many
SELECT id, name, type_id, file_path, description, is_active, created_at, updated_at FROM templates
WHERE type_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListTemplatesByType(ctx context.Context, typeID uuid.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByType, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TypeID,
			&i.FilePath,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates
SET name = $2, type_id = $3, file_path = $4, description = $5, is_active = $6
WHERE id = $1
RETURNING id, name, type_id, file_path, description, is_active, created_at, updated_at
`

type UpdateTemplateParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	TypeID      uuid.UUID   `json:"type_id"`
	FilePath    string      `json:"file_path"`
	Description pgtype.Text `json:"description"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.ID,
		arg.Name,
		arg.TypeID,
		arg.FilePath,
		arg.Description,
		arg.IsActive,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TypeID,
		&i.FilePath,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
